[GOOGLE_CREDS]
type = "service_account"
project_id = "booking-system-436811"
private_key_id = "ac7a5f0d8c68e84ad8ad8f513d98fcd662ab6b8c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC42t/PeKgWyAtG
x+vwHuSnDSUN19TYV/PaG9jbZ+jOJeQvEjQNvwkHvxEgArG0vZP5gOxV1WZAUzgP
QIR9YE1knkgeNRw4VV18pZef8PQJUvw53U6fjg9yCs05qltC6xBCZRu4eX6/6rQa
fG/YKCdgI98mgrP7zyaufSC5zj7Smpiri0AoaD23JP8XS5ysL/WC1mCs7YePtt46
5LwNr94T/NGtmKSHspQcqdkoa+u/u0jpfH1A3ae9UszG8OzhqrtI6swV/G4on4nn
1o7upysXCwx3v8+tWSBeS8P86vOd29AfgpoEx8U6X7pWjDCquLxVhulGvUMKiEwS
zBqTKOspAgMBAAECggEACnv3d6frOKeN5CzQl+TYqRTYxik4nDCY1wT/TqpdDNwf
TgAlTaZJF9RhX0Rn2c1qyBrkzJV24C0YH91T5lyA5zUG+BehCxzkWX521A5xeNnp
Dksb+3auL5SnQR8FYA0+9dUQNm1FoBLqthnaqhLU8OH39RIyrRR5qCnWolMtQvqC
/JmaHGEvKtR5STFGe41thBi+9Z3ad2qP9OeCRLqXSbtkGBzBh9ghAbkb68J42YLd
1LgNNQCvDysuBmd6X5EW5gdlRjjNn3LJAte6ozrKVXvtMJ8Nrw1V1j4wSqk8ubDY
4pTf7KnC0n5uIQi9MXqvkbZhdC2WUxwN8tOifIkCkQKBgQDjniLb4DCm7FVK7wLl
i1IquUfgNU7Hk4r5Z2QgLSd6kJ5IzQL+wEupXIBh1nSI7sqatZPkMGNOpFR4dz9x
D/YLLxCM2PKGJLToYJMT+lu02+KKtSAcsx1RnmU7t8Jniuc3NfbNXuFLel2saeQ1
U9oewrALbgUqppOlHHPsIgPppQKBgQDP57GflTJRKTEU8lFqan9c5jCON4Mx82wy
ABmQOKF1DbAXjATm0oOUDM8yzQPPXFuvZvONw/fC09Qqdx9rfkTgGN44g+dGJaLV
e+rgeb2dMbRo7acMKRDWsvNf68tEUEgZrL987NxjASTuEsB8HchMI3m9OzROnTtP
xw690sWcNQKBgG3DsKO/tTaJ+YetQwRW70TTHKouitMLf5VOGqa5n7QnUW1iD/Ox
38rIZNDJjmEKZoG81pjQDNO7w1BkkR+AxvIVvDFv3WR7BxKYn9SeguLwtoqVVesB
JT5a2A64SvOLtHyXdXEMNDElzU57siVVTnZPBH4+jBdJRSH2WqCgtqpRAoGBAJtW
G4qGaM/nHPrvihEefQamHoVDyMxbee1p0a/GACx7C6SsQ0VK6HCHmY/1SfF2qjJF
k5fKYaW5q34G/vzLnR5qti43r2bj2+Px8C3EB/4ZExiK6BLX4/LmRZzXikoCSbyV
K4VlW8zFIBiY/iQ+BFeO8fiG8bADHjufGM6PWoI5AoGASrx30Sq5QMJYNOdAPy8N
OFumZKWoNIezMw70BX/6qvHEgliCqErjBO32jnnx3D7IXM6mre7LnkY27Gcc5KM+
RIniWrs4rqfB2lQy3ljQGXnHjg/9VYsHMl1LxyC45mcDRPI5iWUArmyCGlcO0j6a
5QSLkSrYP8CNZBVadtFimnw=
-----END PRIVATE KEY-----\n"""
client_email = "booking-holiday-system@booking-system-436811.iam.gserviceaccount.com"
client_id = "112441983221265886236"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/booking-holiday-system%40booking-system-436811.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
